### ISSUE TITLE
Has this article been accepted by a conference?

### ISSUE THREAD

**Issue by PrimoWW** [qingzwang/AudioVisualCrowdCounting#1]
thanks for your great work, I saw it is preprint, but I am very interested

**Comment by qingzwang** [comment]
> thanks for your great work, I saw it is preprint, but I am very interested

We presented the work at the Sight and Sound workshop, CVPR2020, you may find the short version http://sightsound.org/papers/2020/Di_Hu_Does_Ambient_Sound_Help_Audiovisual_Crowd_Counting.pdf and video https://www.youtube.com/watch?v=bk8fm7t7RJU.

Thanks for your interest, if you think the paper is helpful you can just cite the arxiv version and if you have any question, please leave a message.
