### ISSUE TITLE
Original point labels are not available?

### ISSUE THREAD

**Issue by lisosia** [qingzwang/AudioVisualCrowdCounting#2]
@qingzwang 
I checked the dataset and found that there is density map labels but not point labels (set of (x,y)).
Are they available?

**Comment by qingzwang** [comment]
@lisosia 
We have shared the original dot annotations, and you can find them at https://drive.google.com/file/d/1QA_Dn6WNsXDzVexnEC0fx_QgaUzAT9V8/view?usp=sharing.

**Comment by lisosia** [comment]
@qingzwang Hi, thanks for the response. Approval seems to be required, so please approve.
